formatter: markdown table

settings:
  anchor: false
  indent: 4

output:
  file: ../../README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_NFW_DOCS -->
    {{ .Content }}
    <!-- END_TF_NFW_DOCS -->
